#!/usr/bin/env bash

set -euo pipefail

mapfile -t PACKAGES < <(jq -r '.packages[]' packages.json)
for i in "${!PACKAGES[@]}"; do
    # Assign packages to shards round-robin by index so work is spread evenly.
    if (( i % SHARD_COUNT != SHARD_INDEX )); then
        continue
    fi

    pkg="${PACKAGES[i]}"
    echo "::group::$pkg"

    # Clear stale output from the previous package in this loop iteration.
    rm -rf artifacts

    # Snapshot the incompatible-package count before running, so we can tell which
    # entries (if any) Package.ps1 just added for this specific package.
    before_count=$(jq 'length' incompatible.json 2>/dev/null || echo 0)
    pwsh ./Package.ps1 -PackageName "$pkg"

    # Package.ps1 may emit multiple UPM packages per NuGet package (the requested
    # package plus any of its transitive dependencies), so publish each in turn.
    for dir in artifacts/*/; do
        (
            cd "$dir"
            name=$(jq -r .name package.json)
            version=$(jq -r .version package.json)

            # Shared transitive dependencies get regenerated by multiple packages/shards;
            # skip re-publishing a version that's already on the registry to avoid a 409.
            registry_url="https://npm.pkg.github.com/@$REGISTRY_OWNER"
            if npm view "$name@$version" version --registry="$registry_url" >/dev/null 2>&1; then
                echo "$name@$version already published, skipping"
            else
                npm publish --registry="$registry_url"
            fi
        )
    done

    # File an issue for any package that lacks netstandard2.0/2.1 support (skip if one is already open).
    after_count=$(jq 'length' incompatible.json 2>/dev/null || echo 0)
    if [ "$after_count" -gt "$before_count" ]; then
        # Only the newly appended slice belongs to this package; earlier entries were
        # already handled (and possibly already have open issues) in prior iterations.
        jq -c ".[$before_count:$after_count][]" incompatible.json | while read -r entry; do
            id=$(echo "$entry" | jq -r .id)
            version=$(echo "$entry" | jq -r .version)
            requested=$(echo "$entry" | jq -r .requestedPackage)
            title="Incompatible NuGet package: $id"

            # Search for an existing open issue with the same title to avoid duplicate spam on reruns.
            existing=$(gh issue list --state open --search "in:title \"$title\"" --json number --jq '.[0].number')
            if [ -z "$existing" ]; then
                gh issue create --title "$title" --body "NuGet package \`$id\` (version \`$version\`, requested via \`$requested\`) does not provide a netstandard2.0 or netstandard2.1 assembly and cannot be mirrored to UPM."
            fi
        done
    fi
    echo "::endgroup::"
done